# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 21:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default=datetime.time(23, 59, 59, 999999)),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
