# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_auto_20160606_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(default='empty description.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(default='empty event title', max_length=64),
        ),
    ]
