# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_auto_20160703_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.DateField(unique=True, verbose_name="day's happening time"),
        ),
    ]
